import{LoaderCircle}from"lucide-react";import type{ButtonHTMLAttributes,ReactNode}from"react";
export function SectionHeading({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:ReactNode}){return <div className="flex flex-col gap-4 border-b border-[#232328] pb-5 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow?<p className="ui-label mb-1 text-[#FF6B00]">{eyebrow}</p>:null}<h1 className="text-2xl font-bold tracking-[-.02em] text-[#F0F0F0] sm:text-[28px]">{title}</h1><p className="mt-1 max-w-2xl text-[13px] leading-6 text-[#A0A0A8]">{description}</p></div>{action}</div>}
export function Badge({children,tone="neutral"}:{children:ReactNode;tone?:"neutral"|"success"|"warning"|"danger"|"info"|"orange"}){const styles={neutral:"border-[#303038] bg-[#303038] text-[#A0A0A8]",success:"border-[#22C55E33] bg-[#22C55E18] text-[#22C55E]",warning:"border-[#EAB30833] bg-[#EAB30818] text-[#EAB308]",danger:"border-[#EF444433] bg-[#EF444418] text-[#EF4444]",info:"border-[#3B82F633] bg-[#3B82F618] text-[#3B82F6]",orange:"border-[#FF6B0033] bg-[#FF6B0022] text-[#FF6B00]"};return <span className={`inline-flex items-center rounded-[4px] border px-2 py-.5 text-[10px] font-semibold uppercase tracking-[.05em] ${styles[tone]}`}>{children}</span>}
export function GradeBadge({grade}:{grade:string}){const normalized=grade.trim().toUpperCase().replace(/^GRADE\s*/,"");const tone=normalized==="A"?"success":normalized==="B"?"warning":"danger";return <Badge tone={tone}>{grade}</Badge>}
export function StatusBadge({status}:{status:string}){const value=status.toLowerCase();const tone=["active","success","win","winning","mapped","approved","connected"].includes(value)?"success":["paused","pending","medium","tied","partial"].includes(value)?"warning":["error","failed","losing","cancelled","no_match","unmapped","disconnected"].includes(value)?"danger":["processing","in_process","override","manual","running"].includes(value)?"orange":["shipped","info"].includes(value)?"info":"neutral";return <Badge tone={tone}>{status.replaceAll("_"," ")}</Badge>}
export function ActionButton({children,variant="primary",loading=false,className="",...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"ghost"|"danger";loading?:boolean}){const styles={primary:"border-[#FF6B00] bg-[#FF6B00] text-black hover:bg-[#ff812b]",secondary:"border-[#2E2E35] bg-[#141416] text-[#F0F0F0] hover:bg-[#1A1A1E] hover:border-[#606068]",ghost:"border-transparent bg-transparent text-[#A0A0A8] hover:bg-[#1A1A1E] hover:text-[#F0F0F0]",danger:"border-[#EF444433] bg-[#EF444418] text-[#EF4444] hover:border-[#EF4444]"};return <button {...props} disabled={loading||props.disabled} className={`inline-flex min-h-9 items-center justify-center gap-2 rounded-[8px] border px-3.5 py-2 text-[11px] font-semibold uppercase tracking-[.05em] disabled:cursor-not-allowed disabled:border-[#303038] disabled:bg-[#303038] disabled:text-[#606068] ${styles[variant]} ${className}`}>{loading?<LoaderCircle className="h-3.5 w-3.5 animate-spin"/>:null}{children}</button>}
export function PageSkeleton(){return <div className="grid gap-4"><div className="h-20 animate-pulse rounded-[12px] bg-[#141416]"/><div className="grid gap-4 md:grid-cols-3">{[0,1,2].map(value=><div key={value} className="h-36 animate-pulse rounded-[12px] bg-[#141416]"/>)}</div><div className="h-80 animate-pulse rounded-[12px] bg-[#141416]"/></div>}
export function EmptyState({title,description}:{title:string;description:string}){return <div className="flex min-h-52 flex-col items-center justify-center rounded-[12px] border border-dashed border-[#2E2E35] bg-[#0C0C0E44] px-6 text-center"><p className="text-[13px] font-semibold text-[#F0F0F0]">{title}</p><p className="mt-1 max-w-sm text-[12px] leading-5 text-[#606068]">{description}</p></div>}
export function Tooltip({label,children,side="bottom"}:{label:string;children:ReactNode;side?:"top"|"bottom"}){return <span className="group relative inline-flex"><span className="inline-flex">{children}</span><span role="tooltip" className={`pointer-events-none absolute left-1/2 z-50 w-max max-w-52 -translate-x-1/2 rounded-[4px] border border-[#2E2E35] bg-[#0C0C0E] px-2 py-1 text-[10px] font-medium text-[#F0F0F0] opacity-0 shadow-xl transition-opacity duration-150 group-hover:opacity-100 group-focus-within:opacity-100 ${side==="top"?"bottom-full mb-2":"top-full mt-2"}`}>{label}</span></span>}
